import {
  ENTITY_SWAP,
  ERROR_CATEGORY_CONTEXT,
  LABEL_GRANULARITY,
  LATERALITY_SWAP,
  NEGATION_FLIP,
  PARAPHRASE_METEOR,
  TEMPORAL_CHANGE,
} from "./reportExamples";

export const REPORT_PRESETS = [
  NEGATION_FLIP,
  LATERALITY_SWAP,
  TEMPORAL_CHANGE,
  ENTITY_SWAP,
  PARAPHRASE_METEOR,
  LABEL_GRANULARITY,
  ERROR_CATEGORY_CONTEXT,
] as const;
